# This is a basic workflow to help you get started with Actions

name: Android Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the Lucas branch
  pull_request:
    branches: [ main ]
  push:
    branches: [ Lucas ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # android build job
  build:
    # The type of runner that the job will run on
    
    runs-on: ubuntu-latest
    steps:
      
      # Setup the environment
      - name: Setup Checkout
        uses: actions/checkout@v2  
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.8.1'
      - name: Setup Amplify
        shell: bash
        run: npm install -g @aws-amplify/cli@7.6.15
      
      # Build the android artifacts
      - name: Configure Environment
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # Install Amplify, download remote backend configuration, build the flutter release
        run: |
          ./amplify.sh --appid d30wx1kvbjtgdy --envName staging --accessKey "$AWS_ACCESS_KEY_ID" --secretKey "$AWS_SECRET_ACCESS_KEY"
          flutter pub get

      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@v1
        
      - name: Start ChromeDriver
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub --port=4444 &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
      
      - name: Integration Tests
        shell: bash
        run: |
          flutter drive \
            --driver=test_driver/integration_test.dart \
            --target=integration_test/amplify_test.dart \
            -d web-server
            
      - name: Run Unit Tests
        shell: bash
        run: flutter test
       
      - name: Build App
        shell: bash
        run: |
          flutter build appbundle
          flutter build apk --split-per-abi
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: android-builds
          path: |
            build/app/outputs/bundle/release/app-release.aab
            build/app/outputs/flutter-apk/
  
  # release build artifacts        
  # TODO
          
      
